# Generated by Django 4.1.2 on 2022-10-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('identity', models.FileField(upload_to='static/Patient/Identity')),
                ('identitySign', models.CharField(max_length=1024, null=True)),
                ('publicKey', models.FileField(blank=True, null=True, upload_to='static/Patient/Keys')),
                ('profile_pic', models.ImageField(null=True, upload_to='static/Patient/Profile_pics')),
                ('name', models.CharField(max_length=40, null='False')),
                ('email', models.CharField(default='xyz@gmail.com', max_length=40)),
                ('address', models.CharField(max_length=40, null='False')),
                ('mobile', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('userType', models.CharField(max_length=10)),
                ('dateCreated', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/Doctor/')),
                ('license', models.FileField(blank=True, null=True, upload_to='static/Doctor/')),
                ('other_docs', models.FileField(blank=True, null=True, upload_to='static/Doctor/')),
                ('name', models.CharField(max_length=40, null='False')),
                ('email', models.CharField(default='xyz@gmail.com', max_length=40)),
                ('address', models.CharField(max_length=40, null='False')),
                ('mobile', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('userType', models.CharField(max_length=10)),
                ('dateCreated', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
