# Generated by Django 4.1.2 on 2022-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='signVerified',
            field=models.IntegerField(default=0),
        ),
    ]
