# Generated by Django 4.1.2 on 2022-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_patient_signverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='other', max_length=40)),
                ('file', models.FileField(blank=True, upload_to='static/Documents/Upload')),
                ('signature', models.CharField(max_length=1024, null=True)),
                ('publicKey', models.FileField(blank=True, null=True, upload_to='static/Documents/Keys')),
                ('owner', models.CharField(max_length=40)),
                ('sharedWith', models.TextField(null=True)),
            ],
        ),
    ]
