# Generated by Django 4.1.2 on 2022-10-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phoneVerified',
            field=models.IntegerField(default=0),
        ),
    ]
