# Generated by Django 4.1.2 on 2022-10-30 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0005_remove_doctor_other_docs_doctor_identitysign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=40)),
                ('receiver', models.CharField(max_length=40)),
                ('amount', models.CharField(max_length=40)),
                ('remarks', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('name', models.CharField(max_length=40, null='False')),
                ('email', models.CharField(default='xyz@gmail.com', max_length=40)),
                ('license', models.FileField(blank=True, null=True, upload_to='static/Hospital/License')),
                ('identitySign', models.CharField(max_length=1024, null=True)),
                ('publicKey', models.FileField(blank=True, null=True, upload_to='static/Hospital/Keys')),
                ('mobile', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='static/Hospital/pics')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='static/Hospital/pics')),
                ('accountNumber', models.IntegerField(null=True)),
                ('IFSC', models.CharField(max_length=10, null='False')),
                ('accountHolder', models.CharField(max_length=20, null='False')),
                ('type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('medicineList', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('name', models.CharField(max_length=40, null='False')),
                ('email', models.CharField(default='xyz@gmail.com', max_length=40)),
                ('license', models.FileField(blank=True, null=True, upload_to='static/Hospital/License')),
                ('identitySign', models.CharField(max_length=1024, null=True)),
                ('publicKey', models.FileField(blank=True, null=True, upload_to='static/Hospital/Keys')),
                ('mobile', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='static/Hospital/pics')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='static/Hospital/pics')),
                ('type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('name', models.CharField(max_length=40, null='False')),
                ('email', models.CharField(default='xyz@gmail.com', max_length=40)),
                ('license', models.FileField(blank=True, null=True, upload_to='static/Hospital/License')),
                ('identitySign', models.CharField(max_length=1024, null=True)),
                ('publicKey', models.FileField(blank=True, null=True, upload_to='static/Hospital/Keys')),
                ('mobile', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='static/Hospital/pics')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='static/Hospital/pics')),
                ('accountNumber', models.IntegerField(null=True)),
                ('IFSC', models.CharField(max_length=10, null='False')),
                ('accountHolder', models.CharField(max_length=20, null='False')),
                ('type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
