# Generated by Django 4.1.2 on 2022-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_payment_pharmacy_insurance_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='insurance',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='static/Insurance/License'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='static/Insurance/pics'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='static/Insurance/pics'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='publicKey',
            field=models.FileField(blank=True, null=True, upload_to='static/Insurance/Keys'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='static/Pharmacy/License'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='static/Pharmacy/pics'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='static/Pharmacy/pics'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='publicKey',
            field=models.FileField(blank=True, null=True, upload_to='static/Pharmacy/Keys'),
        ),
    ]
