# Generated by Django 4.1.2 on 2022-10-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospital_verified_insurance_verified_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phoneVerified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='signVerified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insurance',
            name='phoneVerified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insurance',
            name='signVerified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phoneVerified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='signVerified',
            field=models.IntegerField(default=0),
        ),
    ]
